config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to => "homes#top"
  get "home/about" => "homes#about"

  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    #render :create
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new    
    book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    book_comment.destroy
    #refroute = Rails.application.routes.recognize_path(request.referer)
    #@book = Book.find(refroute[:id])
    #@book = Book.find(params[:book_id])
    #@book_comment = BookComment.new
    #BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    #render :destroy
    #redirect_to request.referer
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_count.html.erb
コメント数: <%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<%= form_with model:[book, book_comment], local: false do |f| %>
  <%= f.text_area :comment, row:'5', plaseholder: "コメントをここに", class: "w-100" %><br>
  <%= f.submit "送信する", class: "btn btn-base-1 mt-20 pull-right btn-outline-secondary" %>
<% end %>

app/views/book_comments/_index.html.erb
  <table>
    <tbody>
    <% book.book_comments.each do |book_comment| %>
      <tr>
        <td>
          <%= link_to user_path(book_comment.user) do %>
            <%= image_tag book_comment.user.get_profile_image, size:"100x100" %><br>
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= book_comment.comment %></td>
        <td>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>

app/views/book_comments/create.js.erb
$("#comments_area").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#comments_count").html("<%= j(render 'book_comments/count', book: @book) %>");
$("#book_comment_comment").val('');

app/views/book_comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#comments_count").html("<%= j(render 'book_comments/count', book: @book) %>");
$("#book_comment_comment").val('');